291  unit tests to package mapping
OlhenShu/GreenCityMVPTemplate pull request #11
Opened 2023-12-16 09:33 UTC by KizerovDmitriy

2023-12-16 12:00 UTC, DenysLiubchenko requested changes

2023-12-16 12:00 UTC, DenysLiubchenko commented on service/src/test/java/greencity/mapping/MultipartBase64ImageMapperTest.java
MultipartBase64ImageMapper lines covered 88%. Catch block isn`t covered

2023-12-16 21:04 UTC, KizerovDmitriy commented on service/src/test/java/greencity/mapping/MultipartBase64ImageMapperTest.java
100% Coverage

2023-12-17 22:45 UTC, urio999 approved these changes
Cool! Great job, guys

2023-12-18 07:52 UTC, DenysLiubchenko reviewed
Nice

2023-12-18 07:53 UTC, DenysLiubchenko approved these changes

2023-12-22 09:47 UTC, staaankey approved these changes

2023-12-23 13:46 UTC, merged