292  unit tests for service package
OlhenShu/GreenCityMVPTemplate pull request #21
Opened 2023-12-20 15:35 UTC by urio999

2023-12-22 09:24 UTC, staaankey approved these changes

2023-12-23 13:37 UTC, DenysLiubchenko requested changes
I think we dont need to commit 13000 lines of htmlReport

2023-12-23 13:37 UTC, DenysLiubchenko commented on service-api/src/main/java/greencity/dto/search/SearchResponseDto.java
> +//import lombok.Builder;
Delete this comment

2023-12-23 21:31 UTC, urio999 commented on service-api/src/main/java/greencity/dto/search/SearchResponseDto.java
> +//import lombok.Builder;
Commented code deleted

2023-12-28 21:06 UTC, staaankey approved these changes

2023-12-29 10:37 UTC, OleksandrKobetsDev approved these changes
well done

2024-01-09 17:10 UTC, DenysLiubchenko approved these changes

2024-01-09 17:15 UTC, merged